spring:
  application:
    name: tag-zone-service
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    databse-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true
      settings:
        web-allow-athers: true
      path: /h2-console
    datasource:
      url: jdbc:h2:~/test;
      driverClassName: org.h2.Driver
      username: sa
      password:


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

server:
  port: 0

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              basicBinder: TRACE