server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoint:
    web:
      exporsure:
        include: refresh, health, beans, httptrace, busrefresh

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<path>.*),/$\{path}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/sign-up
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET, POST
          filters:
            - RemoveRequestHeader=Cookie
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
        - id: study-service
          uri: lb://STUDY-SERVICE
          predicates:
            - Path= /study-service/**
          filters:
            - AuthorizationHeaderFilter
        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path= /event-service/**
          filters:
            - AuthorizationHeaderFilter
        - id: tag-zone-service
          uri: lb://TAG-ZONE-SERVICE
          predicates:
            - Path= /tag-zone-service/**
          filters:
            - AuthorizationHeaderFilter

token:
  expiration_time: 86400000
  secret: user_token